return {
  "mason-org/mason.nvim",
  opts = {
    ensure_installed = {
      "stylua",
      "shellcheck",
      "shfmt",
      "black",
      "isort",
      "flake8",
      "mypy",
      "pylint",
      "prettierd",
      "eslint_d",
      "typescript-language-server",
      "lua-language-server",
      "gopls",
      "rust-analyzer",
      "clangd",
      "cmake-language-server",
      "bash-language-server",
      "json-lsp",
      "yaml-language-server",
      "html-lsp",
      "css-lsp",
    },
  },
}
